version: '3'

services:
  postgres:
    image: postgres:13
    container_name: co2_calculator_db
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: co2_calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: